# Site settings
title: Hammad M
email: hammad@hamelot.co.uk
description: Multibody Dynamics Research, Among Other Things
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hamelot.co.uk" # the base hostname & protocol for your site
feed_url: "http://hamelot.co.uk/feed.xml"
author: hammad mazhar

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
excerpt_separator: "\n\n\n"
paginate: 5
paginate_path: posts/page:num
gems:      [jekyll-paginate]
future: true