title : Hammad M
tagline: Multibody Dynamics Research, Among Other Things
author :
  name : Hammad Mazhar
  email : hammad@hamelot.co.uk
#  github : username
#  twitter : username
#  feedburner : feedname

navigation :
  - research.html
  - publications.html
  - media.php
  - about.html
  - tags.html
#  - pages.html

plugins:
  sitemap_generator: # all optional
    file_name: sitemap.xml  
  vimeo_video:
